license = "${mod_license}"
issueTrackerURL = "https://github.com/${github_author}/${github_mod_name}"
modLoader="javafml"
loaderVersion="[1,)"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
side="${neoforge_trick_side}"
displayURL = "https://modrinth.com/mod/${github_mod_name}"
logoFile = "icon/icon.png"
authors = "${mod_authors}"
description = '''${mod_description}'''

${neoforge_trick_mixin_configs}

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "mossylib"
type = "required"
versionRange = "[1.4.0,)"
ordering = "NONE"
side = "BOTH"